### ISSUE TITLE
issue about running on linux.

### ISSUE THREAD

**Issue by jingxi0109** [jpmikkers/DHCPServer#16]
Hi JP,
here use your code on linux for iPXE Boot,has failed as below, i know your code run sucsess on windows, for linux can you give some advice?
many thanks.~

DHCP Server start failed, reason 'System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.
   at System.Net.Sockets.SocketPal.WindowsIoctl(SafeSocketHandle handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at System.Net.Sockets.Socket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at GitHub.JPMikkers.DHCP.UDPSocket..ctor(IPEndPoint localEndPoint, Int32 packetSize, Boolean dontFragment, Int16 ttl, OnReceiveDelegate onReceive, OnStopDelegate onStop) in /home/jingxi/Code/autostress/Library/UDPSocket.cs:line 139

**Comment by jpmikkers** [comment]
Hi Jingxi,
On linux, the IOControl method is not supported, you should comment it out (line 139 in UDPSocket.cs)
https://github.com/jpmikkers/DHCPServer/blob/master/DHCPServer/Library/UDPSocket.cs#L139

A prettier solution (on .NET 6) would be to test if we're running on windows before calling IOControl, like so:

    if (OperatingSystem.IsWindows())
    {
        m_Socket.IOControl((IOControlCode)SIO_UDP_CONNRESET, new byte[] { 0, 0, 0, 0 }, null);
    }

My TFTPServer and TFTPClient libraries have the same linux issue, so I'll create a fix for all of those soon.
